import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import data from "./utils/data";

export default function Home() {
  const [search, setSearch] = useState("");
  return (
    <>
      <Head>
        <title>Home-page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 min-h-screen text-white p-9 text-3xl
      flex flex-col justify-center items-center
      "
      >
        <div className=" text-3xl font-bold space-y-3 p-6 border-2 md:text-6xl">
          <p>WANNA MAKE MORE FRIENDS?</p>
          <p className=" text-gray-300">CONFESS TO YOU CRUSH?</p>
          <p>COMPLAIN YOUR SPOT ?</p>
          <p className=" text-gray-300">HAVE FUN HERE!!!</p>
          <div className="flex  items-center">
            <input
              className=" text-3xl rounded-lg bg-inherit border-2 p-3 "
              type="text"
              name=""
              id=""
              placeholder="Search location..."
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>
        <div className=" mt-9 flex flex-wrap justify-center items-center ">
          {data
            .filter((item) => {
              if (search === "") {
                return item;
              } else if (
                item.schoolName.toLowerCase().includes(search.toLowerCase())
              ) {
                return item;
              }
            })
            .map((school, i) => {
              return (
                <div
                  key={i}
                  className=" border-2 rounded-lg w-80 h-96 mx-9 mt-6 p-6"
                >
                  <Link href={`/school/${school.schoolName}`}>
                    <img src={school.img} alt="" className=" w-full h-60" />
                    <p className=" uppercase text-2xl font-mono">
                      {" "}
                      {school.schoolName}
                    </p>
                  </Link>
                </div>
              );
            })}
        </div>
      </div>
    </>
  );
}
