import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import io from "socket.io-client";
import Chat from "../components/Chat";

const socket = io.connect("http://localhost:3001");
function school() {
  const route = useRouter();
  const { school } = route.query;
  const [username, setUsername] = useState("");
  const room = school;
  const [showChat, setShowChat] = useState(false);
  const joinRoom = (e) => {
    e.preventDefault();
    if (username !== "" && room !== "") {
      socket.emit("join_room", room);
      setShowChat(true);
    }
  };

  return (
    <>
      {" "}
      <Head>
        <title>CHAT HERE!!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" min-h-screen space-y-3 rounded-lg bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white flex flex-col justify-center items-center">
        <div className=" text-2xl md:text-6xl font-bold flex justify-center items-center ">
          <p className="w-fit  ">Welcome to {school}'s chat!!!</p>
        </div>
        {!showChat ? (
          <div className=" flex flex-col justify-center items-center">
            <input
              type="text"
              placeholder="YOUR NAME..."
              className="border-2 rounded p-3 text-black"
              onChange={(event) => {
                setUsername(event.target.value);
              }}
            />
            <button
              className=" border-2 mt-6 rounded-lg p-3 hover:bg-pink-400"
              onClick={joinRoom}
            >
              Start Chat
            </button>
          </div>
        ) : (
          <Chat socket={socket} username={username} room={room} />
        )}
      </div>
    </>
  );
}

export default school;
