import Head from "next/head";
import React from "react";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header className=" bg-purple-300">header</header>
        <main>{children}</main>
        <footer>footer</footer>
      </div>
    </>
  );
}

export default Layout;
